### ISSUE TITLE
Wrong cursor name + missing cursor

### ISSUE THREAD

**Issue by junior2308** [khayalhus/win2xcur-batch#1]
Within "map.json"

**Rename =** 

"07-Target" to "07-Precision"

**Add =** 

"cell" on "07-Precision"
"not-allowed" and "no-drop" on "08-Unavailable"
"ne-resize" and "nesw-resize" on "14-Diagonal Resize 2"

I think that should be it, at least I did not find anything else missing aside from those.
Thanks!

**Comment by khayalhus** [comment]
Thank you very much for pointing out these issues. I have addressed them in [v0.1.1](https://github.com/khayalhus/win2xcur-batch/releases/tag/v0.1.1)
